import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FC',
  },
  scrollIndicator: {
    height: 5,
    width: 60,
    backgroundColor: '#E8ECEF',
    borderRadius: 4,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  emptyText: {
    fontSize: 16,
    color: '#8896AB',
    textAlign: 'center',
    marginTop: 10,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E8ECEF',
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  headerTxt: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2E3A59',
    marginLeft: 15,
  },
  BackIcon: {
    width: 22,
    height: 22,
  },
  sectionTabsContainer: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  sectionTab: {
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 25,
    marginRight: 12,
    backgroundColor: '#FFFFFF',
    width: 120,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  activeSectionTab: {
    backgroundColor: '#4361EE',
    elevation: 4,
    shadowOpacity: 0.2,
  },
  sectionTabText: {
    fontSize: 15,
    color: '#555B6E',
    fontWeight: '600',
    textAlign: 'center',
  },
  activeSectionTabText: {
    color: '#FFFFFF',
  },
  subjectList: {
    flex: 1,
    padding: 18,
  },
  subjectCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F0F4F8',
  },
  subjectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F8',
  },
  subjectName: {
    fontWeight: '700',
    fontSize: 17,
    color: '#2E3A59',
    letterSpacing: 0.2,
  },
  actionButtons: {
    flexDirection: 'row',
  },
  actionButton: {
    padding: 8,
    marginLeft: 12,
    backgroundColor: '#F8F9FC',
    borderRadius: 8,
  },
  categoryContainer: {
    padding: 12,
    paddingTop: 8,
  },
  categoryItemWrapper: {
    backgroundColor: '#F8F9FC',
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#ECF0F4',
    overflow: 'hidden',
  },
  categoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: '#F8F9FC',
  },
  categoryName: {
    color: '#505A72',
    fontSize: 15,
    fontWeight: '600',
  },
  subActivityContainer: {
    paddingLeft: 35,
    paddingRight: 15,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#ECF0F4',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  subActivityText: {
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  addSubCategory: {
    padding: 6,
    backgroundColor: '#E6F7FF',
    borderRadius: 6,
  },
  removeCategory: {
    padding: 6,
    backgroundColor: '#FEF2F2',
    borderRadius: 6,
  },
  floatingButton: {
    position: 'absolute',
    right: 26,
    bottom: 26,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4361EE',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#4361EE',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    zIndex: 999,
  },
  floatingMenu: {
    position: 'absolute',
    right: 26,
    bottom: 96,
    width: 220,
    backgroundColor: 'transparent',
    borderRadius: 12,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    overflow: 'hidden',
    zIndex: 998,
  },
  menuButton: {
    backgroundColor: '#4361EE',
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 2,
    alignItems: 'center',
    borderRadius: 10,
  },
  menuButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(14, 23, 38, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  listModalContainer: {
    width: 300,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    maxHeight: '70%',
    elevation: 8,
    paddingBottom: 6,
  },
  listModalItem: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F8',
    flexDirection: 'row',
    alignItems: 'center',
  },
  listModalItemText: {
    fontSize: 16,
    color: '#2E3A59',
    fontWeight: '500',
    flex: 1,
    letterSpacing: 0.2,
  },
  formModalContainer: {
    width: '92%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingTop: 25,
    paddingBottom: 28,
    paddingHorizontal: 24,
    alignItems: 'center',
    elevation: 8,
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 20,
    alignSelf: 'flex-start',
    color: '#2E3A59',
    letterSpacing: 0.2,
  },
  input: {
    width: '100%',
    height: 52,
    borderWidth: 1.5,
    borderColor: '#DCE2E8',
    borderRadius: 12,
    paddingHorizontal: 16,
    marginBottom: 16,
    color: '#2E3A59',
    backgroundColor: '#F9FAFC',
    fontSize: 15,
    fontWeight: '500',
    flex: 1,
  },
  addMoreButton: {
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#4361EE',
    borderRadius: 12,
    marginBottom: 22,
    backgroundColor: 'rgba(67, 97, 238, 0.06)',
  },
  addMoreButtonText: {
    color: '#4361EE',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  enrollButton: {
    width: '100%',
    height: 54,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#4361EE',
    borderRadius: 12,
    elevation: 4,
  },
  enrollButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
  },
  modalScrollContainer: {
    width: '100%',
    maxHeight: 280,
    marginBottom: 18,
    borderRadius: 12,
    overflow: 'hidden',
  },
  modalScrollContent: {
    paddingBottom: 15,
    paddingRight: 5,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
    width: '100%',
    backgroundColor: '#F9FAFC',
    borderRadius: 12,
    paddingVertical: 4,
    paddingHorizontal: 2,
    borderWidth: 0.5,
    borderColor: '#E8ECEF',
  },
  removeInputButton: {
    marginLeft: 12,
    backgroundColor: '#FEF2F2',
    borderRadius: 20,
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeInputButtonText: {
    fontSize: 20,
    color: '#E53E3E',
    fontWeight: '600',
  },
});

export default styles;