import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    backgroundColor: '#F8F9FB',
    flex: 1,
    paddingBottom: 10,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    // paddingTop: 50,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E8E8E8',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  headerText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1A1A1A',
    letterSpacing: 0.5,
    flex: 1,
    textAlign: 'center',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8F9FB',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  backButtonText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  languageScrollContainer: {
    flexGrow: 0,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginHorizontal: 20,
    marginVertical: 8,
  },
  languageButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginHorizontal: 6,
    borderRadius: 25,
    backgroundColor: '#F0F0F3',
    borderWidth: 1,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  selectedLanguage: {
    backgroundColor: '#3557FF',
    borderColor: '#3557FF',
    shadowColor: '#3557FF',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  languageText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#4A4A4A',
  },
  selectedLanguageText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  mainScrollView: {
    flex: 1, 
  },
  timeline: {
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  levelContainer: {
    marginBottom: 24,
  },
  levelHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  timelineLeft: {
    alignItems: 'center',
    width: 48,
    paddingRight: 8,
  },
  levelBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  completedLevelBadge: {
    backgroundColor: '#4CAF50',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  activeLevelBadge: {
    backgroundColor: '#3557FF',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  inactiveLevelBadge: {
    backgroundColor: '#E8E8E8',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  levelNumber: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 16,
  },
  inactiveLevelNumber: {
    color: '#9E9E9E',
    fontWeight: '700',
    fontSize: 16,
  },
  timelineLine: {
    width: 3,
    flex: 1,
    backgroundColor: '#E0E0E0',
    borderRadius: 1.5,
  },
  completedTimelineLine: {
    backgroundColor: '#4CAF50',
  },
  activeTimelineLine: {
    backgroundColor: '#3557FF',
  },
  levelContentContainer: {
    flex: 1,
    paddingBottom: 20,
  },
  levelTitle: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 16,
    color: '#1A1A1A',
    letterSpacing: 0.3,
  },
  tabsCard: {
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    marginHorizontal: 4,
  },
  tabContainer: {
    flexDirection: 'row',
    height: 48,
    backgroundColor: '#F8F9FB',
    borderRadius: 12,
    margin: 6,
    padding: 3,
  },
  tab: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginHorizontal: 1,
  },
  activeTab: {
    backgroundColor: '#3557FF',
    shadowColor: '#3557FF',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#6B7280',
  },
  activeTabText: {
    color: '#FFFFFF',
    fontWeight: '600',
  },
  contentContainer: {
    padding: 16,
  },
  pdfItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 4,
    borderRadius: 12,
    backgroundColor: '#F8F9FB',
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  pdfIconContainer: {
    marginRight: 16,
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pdfName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500',
    color: '#1A1A1A',
    lineHeight: 20,
  },
  downloadButton: {
    padding: 12,
    borderRadius: 12,
    // backgroundColor: '#3557FF',
    // shadowColor: '#3557FF',
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.2,
    // shadowRadius: 4,
    // elevation: 2,
  },
  downloadButtonText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  
  emptyStateText: {
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 16,
    fontWeight: '500',
    padding: 24,
    lineHeight: 24,
  },
  bottomNav: {
    height: 60,
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#E8E8E8',
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 8,
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  activeNavItem: {
    borderTopWidth: 3,
    borderTopColor: '#3557FF',
  },
  navText: {
    fontSize: 12,
    color: '#9CA3AF',
    marginTop: 4,
    fontWeight: '500',
  },
  activeNavText: {
    color: '#3557FF',
    fontSize: 12,
    marginTop: 4,
    fontWeight: '600',
  },
  // Additional utility styles
  progressIndicator: {
    backgroundColor: '#3557FF',
    height: 4,
    borderRadius: 2,
    marginVertical: 8,
  },
  levelProgress: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
    fontWeight: '500',
  },
  completedBadge: {
    backgroundColor: '#10B981',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  completedBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
});

export default styles;