import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F9FC',
  },
  scrollIndicator: {
    height: 4,
    width: 40,
    backgroundColor: '#CBD5E1',
    borderRadius: 4,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
  },
  emptyText: {
    fontSize: 16,
    color: '#8896AB',
    textAlign: 'center',
    marginTop: 10,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E8ECEF',
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  headerTxt: {
    fontSize: 22,
    fontWeight: '700',
    color: '#2E3A59',
    marginLeft: 15,
  },
  BackIcon: {
    width: 22,
    height: 22,
  },
  sectionTabsContainer: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  sectionTab: {
    paddingHorizontal: 22,
    paddingVertical: 14,
    borderRadius: 25,
    marginRight: 12,
    backgroundColor: '#FFFFFF',
    width: 120,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  activeSectionTab: {
    backgroundColor: '#4361EE',
    elevation: 4,
    shadowOpacity: 0.2,
  },
  sectionTabText: {
    fontSize: 15,
    color: '#555B6E',
    fontWeight: '600',
    textAlign: 'center',
  },
  activeSectionTabText: {
    color: '#FFFFFF',
  },
  subjectList: {
    flex: 1,
    padding: 18,
  },
  subjectCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    marginBottom: 18,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#F0F4F8',
  },
  subjectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F8',
  },
  subjectName: {
    fontWeight: '700',
    fontSize: 17,
    color: '#2E3A59',
    letterSpacing: 0.2,
  },
  actionButtons: {
    flexDirection: 'row',
  },
  actionButton: {
    padding: 8,
    marginLeft: 12,
    backgroundColor: '#F8F9FC',
    borderRadius: 8,
  },
  categoryContainer: {
    padding: 12,
    paddingTop: 8,
  },
  categoryItemWrapper: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: '#E3E8EF',
    overflow: 'hidden',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  nestedContainer: {
    backgroundColor: '#FAFBFC',
    borderTopWidth: 1,
    borderTopColor: '#E8ECEF',
  },
  categoryItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: '#F0F5FF',
    borderLeftWidth: 4,
    borderLeftColor: '#4361EE',
    minHeight: 50,
  },
  categoryName: {
    color: '#2E3A59',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  subActivityContainer: {
    paddingLeft: 24,
    paddingRight: 15,
    paddingVertical: 12,
    backgroundColor: '#FAFBFC',
    borderTopWidth: 1,
    borderTopColor: '#E8ECEF',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  subActivityText: {
    fontSize: 14,
    color: '#505A72',
    fontWeight: '500',
    flex: 1,
  },
  addSubCategory: {
    padding: 6,
    backgroundColor: '#E6F7FF',
    borderRadius: 6,
  },
  removeCategory: {
    padding: 6,
    backgroundColor: '#FEF2F2',
    borderRadius: 6,
  },
  removeSubCategory: {
    padding: 5,
    backgroundColor: '#FEE2E2',
    borderRadius: 5,
  },
  floatingButton: {
    position: 'absolute',
    right: 26,
    bottom: 26,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#4361EE',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#4361EE',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    zIndex: 999,
  },
  floatingMenu: {
    position: 'absolute',
    right: 26,
    bottom: 96,
    width: 220,
    backgroundColor: 'transparent',
    borderRadius: 12,
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    overflow: 'hidden',
    zIndex: 998,
  },
  menuButton: {
    backgroundColor: '#4361EE',
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 2,
    alignItems: 'center',
    borderRadius: 10,
  },
  menuButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    backdropFilter: 'blur(4px)',
  },
  listModalContainer: {
    width: '85%',
    maxWidth: 420,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    maxHeight: '75%',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    paddingBottom: 12,
  },
  listModalItem: {
    paddingVertical: 18,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    transition: 'all 0.2s',
  },
  listModalItemText: {
    fontSize: 16,
    color: '#1E293B',
    fontWeight: '500',
    flex: 1,
    letterSpacing: 0.3,
  },
  formModalContainer: {
    width: '90%',
    maxWidth: 480,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingTop: 32,
    paddingBottom: 32,
    paddingHorizontal: 28,
    alignItems: 'center',
    elevation: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    maxHeight: '85%',
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 24,
    alignSelf: 'flex-start',
    color: '#0F172A',
    letterSpacing: 0.3,
  },
  input: {
    width: '100%',
    height: 54,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderRadius: 14,
    paddingHorizontal: 18,
    marginBottom: 16,
    color: '#0F172A',
    backgroundColor: '#F8FAFC',
    fontSize: 15,
    fontWeight: '500',
    flex: 1,
  },
  addMoreButton: {
    width: '100%',
    height: 52,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#3B82F6',
    borderRadius: 14,
    marginBottom: 20,
    backgroundColor: 'rgba(59, 130, 246, 0.05)',
  },
  addMoreButtonText: {
    color: '#3B82F6',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  enrollButton: {
    width: '100%',
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#3B82F6',
    borderRadius: 14,
    elevation: 4,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  enrollButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  // Generic select/confirm button used in selection modals (Subjects/Activities/Sub-activities)
  selectButton: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#3B82F6',
    elevation: 3,
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  selectButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  modalScrollContainer: {
    width: '100%',
    maxHeight: 320,
    marginBottom: 20,
    borderRadius: 14,
    overflow: 'hidden',
  },
  modalScrollContent: {
    paddingBottom: 12,
    paddingRight: 4,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
    backgroundColor: '#F8FAFC',
    borderRadius: 14,
    paddingVertical: 6,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  removeInputButton: {
    marginLeft: 12,
    backgroundColor: '#FEE2E2',
    borderRadius: 24,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 1,
  },
  removeInputButtonText: {
    fontSize: 22,
    color: '#DC2626',
    fontWeight: '700',
  },
  actionMenuBar: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E8ECEF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  actionMenuContent: {
    flexDirection: 'row',
    gap: 10,
    paddingRight: 16,
  },
  actionMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    gap: 6,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  actionMenuItemText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  modalHeader: {
    width: '100%',
    paddingHorizontal: 24,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    backgroundColor: '#FAFBFC',
  },
  modalHeaderTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0F172A',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  modalHeaderSubtitle: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 6,
    fontWeight: '500',
  },
  checkboxContainer: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxChecked: {
    borderColor: '#3B82F6',
    backgroundColor: '#3B82F6',
  },
  checkboxUnchecked: {
    borderColor: '#CBD5E1',
    backgroundColor: 'transparent',
  },
  checkboxIcon: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '700',
  },
});

export default styles;