import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        padding: 16,
    },
    activityHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 10,
        marginBottom: 20,
    },
    homeIcon: {
        marginRight: 15,
    },
    activityText: {
        fontSize: wp('5.5%'),
        fontWeight: 'bold',
        color: '#333',
    },
    searchView: {
        marginBottom: 20,
    },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 15,
        height: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    searchIcon: {
        marginRight: 10,
    },
    searchInput: {
        flex: 1,
        fontSize: wp('3.8%'),
        color: '#333',
    },
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    row: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    profilePic: {
        width: wp('13%'),
        height: wp('13%'),
        borderRadius: wp('6.5%'),
        marginRight: 12,
        backgroundColor: '#E8EAED',
        borderWidth: 1.5,
        borderColor: '#E0E0E0',
    },
    title: {
        fontSize: wp('4.2%'),
        fontWeight: 'bold',
        color: '#333333',
        marginBottom: 3,
    },
    stdid: {
        fontSize: wp('3.6%'),
        color: '#666666',
        fontWeight: '500',
    },
    date: {
        fontSize: wp('3.5%'),
        color: '#888888',
        backgroundColor: '#F0F0F0',
        paddingVertical: 5,
        paddingHorizontal: 10,
        borderRadius: 12,
        overflow: 'hidden',
    },
    reasonTitle: {
        fontSize: wp('3.8%'),
        fontWeight: '600',
        color: '#444444',
        marginBottom: 8,
    },
    reasonBox: {
        backgroundColor: '#F9F9F9',
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    reasonText: {
        fontSize: wp('3.7%'),
        color: '#444444',
        lineHeight: wp('5.5%'),
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 4,
    },
    registeredText: {
        fontSize: wp('3.6%'),
        color: '#666666',
        fontStyle: 'italic',
    },
    callButton: {
        width: wp('10%'),
        height: wp('10%'),
        borderRadius: wp('5%'),
        backgroundColor: '#4CAF50',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    chatButton: {
        width: wp('10%'),
        height: wp('10%'),
        borderRadius: wp('5%'),
        backgroundColor: '#2196F3',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 5,
        shadowColor: '#2196F3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    activityIcons: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        alignItems: 'center',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: '85%',
        maxHeight: '80%',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 20,
        textAlign: 'center',
    },
    inputContainer: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 6,
        color: '#333',
    },
    textInput: {
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 14,
        backgroundColor: '#f9f9f9',
    },
    registerButton: {
        backgroundColor: '#3366ff',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
        marginTop: 10,
    },
    registerButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },

    // Confirmation modal styles
    confirmModalOverlay: {
        flex: 1,
        backgroundColor: '#fff',
    },
    confirmModalContent: {
        flex: 1,
        padding: 20,
        alignItems: 'center',
    },
    confirmAvatar: {
        width: 60,
        height: 60,
        borderRadius: 30,
        marginBottom: 12,
    },
    confirmTitle: {
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 4,
    },
    confirmSubtitle: {
        fontSize: 16,
        color: '#666',
        marginBottom: 4,
    },
    confirmLabel: {
        fontSize: 14,
        color: '#333',
        marginBottom: 24,
    },
    confirmReasonContainer: {
        width: '100%',
        backgroundColor: '#f9f9f9',
        borderRadius: 8,
        padding: 16,
        marginBottom: 30,
    },
    confirmReasonTitle: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
    },
    confirmReasonText: {
        fontSize: 14,
        lineHeight: 20,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 20,
    },
    registerButton: {
        backgroundColor: '#3366ff',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 24,
    },
    registerButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    cancelButton: {
        backgroundColor: '#ccc',
        borderRadius: 8,
        paddingVertical: 12,
        paddingHorizontal: 24,
    },
    cancelButtonText: {
        color: '#333',
        fontSize: 16,
        fontWeight: '600',
    },

    AddIcon: {
        position: 'absolute',
        bottom: 10,
        right: 20,
        padding: 20,
        backgroundColor: '#0C36FF',
        borderRadius: 50,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        fontSize: wp('4%'),
        color: '#888',
        textAlign: 'center',
        marginTop: 20,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 10,
        color: '#666',
        fontSize: wp('3.8%'),
    },
    // Student selection modal styles
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    modalHeaderTitle: {
        fontSize: wp('5%'),
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 0,
        textAlign: 'left',
    },
    modalCloseButton: {
        fontSize: wp('5%'),
        fontWeight: 'bold',
        color: '#777',
    },
    studentItem: {
        padding: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
        flexDirection: 'row',
        alignItems: 'center',
    },
    studentAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#E8EAED',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    studentAvatarText: {
        fontWeight: 'bold',
        color: '#444',
    },
    studentInfo: {
        flex: 1,
    },
    studentName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    studentDetails: {
        fontSize: 14,
        color: '#666',
    }
});

export default styles;
