import {StyleSheet} from 'react-native';
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fafafa',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 10,
    paddingTop: 32,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    backgroundColor: '#FAFAFA',
    flexDirection: 'row',
    alignItems: 'flex-end',
    borderColor: '#00000080',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333333',
  },
  backButton: {
    paddingRight: 10,
    paddingTop: 10,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    borderRadius: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E3E3E3',
  },
  MentorDayDetails: {
    backgroundColor: '#fff',
    margin: 18,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 1,
    shadowRadius: 7,
    marginBottom: -4,
  },
  avatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    margin:10,
  },
  mentorInfo: {
    paddingVertical: 15,
    borderLeftWidth: 1,
    borderLeftColor: '#E3E3E3',
    padding: 10,
  },
  infoLabel: {
    fontSize: 14,
    marginBottom: 4,
    color: '#000',
    fontWeight: '700',
  },
  statsContainer: {
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },

  statBox: {
    borderRadius: 10,
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
    marginHorizontal: 4,
  },
  statValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#000',
  },
  statLabel: {
    fontSize: 12,
    color: '#000',
    fontWeight: '600',
  },
  infoBox: {
    marginHorizontal: 18,
    marginVertical: 10,
    borderRadius: 10,
    padding: 16,
    backgroundColor: '#fff',
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 1,
  },
  infoColumn: {
    flex: 1,
    flexDirection: 'row',
  },
  infoTitle: {
    marginTop: 3,
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
    marginLeft: 5,
  },
  infoTitle1: {
    marginTop: 3,
    fontSize: 12,
    color: '#666',
    fontWeight: '600',
    marginLeft: 30,
  },
  infoValue: {
    fontSize: 12,
    marginTop: 4,
    marginLeft: 6,
    color: '#000',
    fontWeight: '600',
  },

  penicon: {
    marginTop: 5,
    marginLeft: 5,
  },
  scheduleSection: {
    backgroundColor: '#fff',
    padding: 16,
    marginTop: 10,
    width: '95%',
    margin: 10,
    borderRadius: 10,
    marginBottom: -20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 7,
    color: '#000',
  },
  dateNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  dateNavigationControls: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  todayText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    marginRight: 5,
  },
  dateNavArrow: {
    fontSize: 18,
    fontWeight: '600',
    color: '#666',
    paddingHorizontal: 10,
  },
  dateButton: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
  },
  dateText: {
    fontSize: 14,
    color: '#000',
    fontWeight: '600',
  },
  assignButton: {
    marginLeft: 10,
  },
  classItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
    borderRadius: 8,
    backgroundColor: '#F7F7F7',
    marginBottom: 7,

    margin: 10,
  },
  
  classDetails: {
    marginLeft: 5,
  },
  subjectText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#000',
  },
  gradeText: {
    fontSize: 12,
    marginTop: 4,
    color: '#666',
    fontWeight: '600',
  },
  typeText: {
    fontSize: 12,
    color: '#ff9800',
    marginTop: 4,
    fontWeight: '600',
  },
  timeText: {
    fontSize: 12,
    fontWeight: '600',
    marginRight: 5,
    color: '#000',
  },
  shedulesContainer: {
    flex: 1,
    backgroundColor: '#fff',
    marginTop: 0,
    margin: 18,
    borderRadius: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '70%',
  },
  calendarModalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 15,
    width: '90%',
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
    marginBottom: 15,
    textAlign: 'center',
  },
  subjectItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  selectedSubject: {
    backgroundColor: '#F0F7FF',
  },
  selectedSubjectText: {
    color: '#0066CC',
    fontWeight: '500',
  },
  checkmark: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#0066CC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmarkText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 12,
    marginRight: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#666666',
    fontWeight: '500',
  },
  applyButton: {
    flex: 1,
    paddingVertical: 12,
    marginLeft: 10,
    borderRadius: 5,
    backgroundColor: '#0066CC',
    alignItems: 'center',
  },
  applyButtonText: {
    color: 'white',
    fontWeight: '500',
  },
  deleteIcon: {
    marginLeft: 10,
    color: '#FF6B6B',
  },
  homeButtonContainer: {
    position: 'absolute',
    bottom: 30,
    right: 25,
  },
  // Add new styles for session modal
  sessionModalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  sessionModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  sessionModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#000',
    marginLeft: 10,
  },
  sessionList: {
    maxHeight: 350,
  },
  sessionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  checkboxContainer: {
    marginRight: 10,
  },
  sessionText: {
    fontSize: 16,
    color: '#000',
    fontWeight: '500',
  },
  allotButton: {
    marginTop: 20,
    backgroundColor: '#0C36FF',
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: 'center',
  },
  allotButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  // Add new styles for faculty modal
  facultyModalContent: {
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  searchContainer: {
    marginBottom: 15,
  },
  searchBox: {
    backgroundColor: '#e8e8e8',
    padding: 12,
    borderRadius: 10,
  },
  facultyList: {
    maxHeight: 350,
  },
  facultyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  selectedFacultyItem: {
    backgroundColor: '#F0F7FF',
  },
  facultyDetails: {
    flex: 1,
  },
  staffName: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    gap: 6,
  },
  facultyName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#000',
  },
  hatContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  facultySpec: {
    fontSize: 14,
    color: '#666',
  },
  selectButton: {
    marginTop: 15,
    backgroundColor: '#0C36FF',
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: 'center',
  },
  selectButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
export default styles;
