import { StyleSheet } from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('5%'),
    paddingVertical: hp('2%'),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  headerText: {
    fontSize: wp('5.5%'),
    fontWeight: '700',
    marginLeft: wp('3%'),
    color: '#1E293B',
    letterSpacing: 0.5,
  },
  backButton: {
    padding: wp('2%'),
    borderRadius: wp('2%'),
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  headerBorder: {
    height: 1,
    backgroundColor: '#E2E8F0',
    marginHorizontal: wp('4%'),
    marginTop: hp('1%'),
  },

  // Session Card Styles
  sessionCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp('4%'),
    padding: wp('5%'),
    marginHorizontal: wp('4%'),
    marginVertical: hp('1%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  sessionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: hp('1.5%'),
  },
  subjectContainer: {
    flex: 1,
    marginRight: wp('4%'),
  },
  subject: {
    fontSize: wp('5.5%'),
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: hp('0.5%'),
    letterSpacing: 0.3,
  },
  sessionMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: wp('2%'),
    marginTop: hp('0.5%'),
  },
  gradeText: {
    fontSize: wp('3.8%'),
    fontWeight: '500',
    color: '#64748B',
  },
  academicBadge: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: wp('2.5%'),
    paddingVertical: hp('0.5%'),
    borderRadius: wp('4%'),
    borderWidth: 1,
    borderColor: '#BFDBFE',
  },
  academicText: {
    fontSize: wp('3.2%'),
    fontWeight: '600',
    color: '#1D4ED8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  timeContainer: {
    alignItems: 'flex-end',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('1%'),
    borderRadius: wp('2%'),
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  timeText: {
    fontSize: wp('4%'),
    fontWeight: '600',
    color: '#475569',
  },
  durationText: {
    fontSize: wp('3.5%'),
    fontWeight: '500',
    color: '#6B7280',
    marginTop: hp('0.3%'),
  },

  // Status Indicator Styles
  statusIndicator: {
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.8%'),
    borderRadius: wp('5%'),
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: wp('25%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  statusText: {
    fontSize: wp('3.2%'),
    fontWeight: '700',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  
  // Topic and Materials Styles
  topicContainer: {
    marginTop: hp('1.5%'),
    paddingTop: hp('1.5%'),
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  topicLabel: {
    fontSize: wp('3.5%'),
    fontWeight: '600',
    color: '#64748B',
    marginBottom: hp('0.5%'),
  },
  topicHierarchy: {
    fontSize: wp('4%'),
    fontWeight: '500',
    color: '#374151',
    lineHeight: wp('5.5%'),
  },
  materialsContainer: {
    marginTop: hp('1.5%'),
    paddingTop: hp('1.5%'),
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
  },
  materialsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1%'),
    backgroundColor: '#F1F5F9',
    borderRadius: wp('2%'),
    borderWidth: 1,
    borderColor: '#CBD5E1',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  materialsButtonText: {
    color: '#475569',
    fontSize: wp('3.5%'),
    fontWeight: '600',
    marginLeft: wp('2%'),
  },
  
  // Progress Bar Styles
  progressContainer: {
    height: hp('1%'),
    backgroundColor: '#E5E7EB',
    borderRadius: hp('0.5%'),
    overflow: 'hidden',
    marginBottom: hp('1%'),
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#10B981',
    borderRadius: hp('0.5%'),
  },
  progressText: {
    fontSize: wp('3.5%'),
    color: '#6B7280',
    fontWeight: '500',
  },
  
  // Students Section Styles
  studentsContainer: {
    flex: 1,
    backgroundColor: '#F8FAFC',
    marginTop: hp('1%'),
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp('5%'),
    paddingVertical: hp('1.5%'),
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  sectionTitle: {
    fontSize: wp('4.5%'),
    fontWeight: '700',
    color: '#1E293B',
  },
  studentCount: {
    fontSize: wp('3.5%'),
    fontWeight: '500',
    color: '#64748B',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: wp('2.5%'),
    paddingVertical: hp('0.5%'),
    borderRadius: wp('3%'),
  },
  scrollContainer: {
    paddingHorizontal: wp('4%'),
    paddingTop: hp('1%'),
    paddingBottom: hp('2%'),
  },

  // Student Profile Card Styles
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: wp('4%'),
    padding: wp('4%'),
    marginBottom: hp('1.5%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  profileCardOnLeave: {
    backgroundColor: '#FEF3C7',
    borderColor: '#FCD34D',
    opacity: 0.8,
  },
  profileImg: {
    width: wp('14%'),
    height: wp('14%'),
    borderRadius: wp('7%'),
    marginRight: wp('4%'),
    borderWidth: 2,
    borderColor: '#E5E7EB',
  },
  studentInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: wp('4%'),
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: hp('0.2%'),
  },
  profileId: {
    fontSize: wp('3.2%'),
    color: '#64748B',
    fontWeight: '500',
    marginBottom: hp('0.2%'),
  },
  leaveIndicator: {
    fontSize: wp('3%'),
    color: '#D97706',
    fontWeight: '600',
    fontStyle: 'italic',
  },

  // Performance and Action Styles
  performanceContainer: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    minWidth: wp('25%'),
  },
  performanceStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.8%'),
    borderRadius: wp('4%'),
    borderWidth: 1,
    borderColor: '#BBF7D0',
  },
  performanceText: {
    fontSize: wp('3.5%'),
    fontWeight: '700',
    marginRight: wp('2%'),
  },
  editButton: {
    padding: wp('1%'),
    borderRadius: wp('2%'),
    backgroundColor: '#F3F4F6',
  },
  performanceButtons: {
    alignItems: 'flex-end',
    gap: hp('0.5%'),
  },
  markInputButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('0.8%'),
    borderRadius: wp('3%'),
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  markInputButtonText: {
    color: '#FFFFFF',
    fontSize: wp('3.2%'),
    fontWeight: '600',
  },
  absentButton: {
    backgroundColor: '#F3F4F6',
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.6%'),
    borderRadius: wp('3%'),
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  absentButtonActive: {
    backgroundColor: '#FEF2F2',
    borderColor: '#FECACA',
  },
  absentButtonText: {
    color: '#6B7280',
    fontSize: wp('3%'),
    fontWeight: '500',
  },
  absentButtonTextActive: {
    color: '#DC2626',
    fontWeight: '600',
  },

  // Action Button Styles
  actionButtonContainer: {
    paddingHorizontal: wp('5%'),
    paddingVertical: hp('2%'),
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 5,
  },
  actionButton: {
    backgroundColor: '#3B82F6',
    borderRadius: wp('3%'),
    paddingVertical: hp('1.8%'),
    paddingHorizontal: wp('6%'),
    alignItems: 'center',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  actionButtonDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0.1,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: wp('4.2%'),
    fontWeight: '700',
    letterSpacing: 0.5,
  },

  // Batch Styles
  batchContainer: {
    marginBottom: hp('2%'),
  },
  batchHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.2%'),
    borderRadius: wp('3%'),
    borderWidth: 1,
    borderColor: '#E2E8F0',
    marginBottom: hp('0.5%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  batchTitle: {
    flex: 1,
    fontSize: wp('4%'),
    fontWeight: '700',
    color: '#374151',
  },
  batchCount: {
    fontSize: wp('3.2%'),
    color: '#6B7280',
    marginRight: wp('2%'),
  },
  expandIcon: {
    fontSize: wp('4%'),
    color: '#9CA3AF',
  },
  batchStudents: {
    paddingLeft: wp('2%'),
  },

  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  feedbackModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp('6%'),
    padding: wp('6%'),
    margin: wp('5%'),
    maxHeight: '60%',
    minWidth: wp('80%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 15,
  },
  modalHeader: {
    alignItems: 'center',
    marginBottom: hp('2%'),
  },
  modalHandle: {
    width: wp('12%'),
    height: hp('0.5%'),
    backgroundColor: '#D1D5DB',
    borderRadius: wp('2%'),
    alignSelf: 'center',
    marginBottom: hp('2%'),
  },
  modalTitle: {
    fontSize: wp('5%'),
    fontWeight: '700',
    color: '#1E293B',
    textAlign: 'center',
    marginBottom: hp('0.5%'),
  },
  modalQuestion: {
    fontSize: wp('3.8%'),
    color: '#6B7280',
    textAlign: 'center',
    marginTop: hp('1%'),
    lineHeight: wp('5%'),
  },
  markInputContainer: {
    alignItems: 'center',
    marginVertical: hp('3%'),
  },
  markInputField: {
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: wp('3%'),
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.5%'),
    fontSize: wp('5%'),
    fontWeight: '600',
    textAlign: 'center',
    minWidth: wp('30%'),
    backgroundColor: '#F9FAFB',
  },
  totalMarksText: {
    fontSize: wp('3.5%'),
    color: '#6B7280',
    marginTop: hp('0.8%'),
    fontWeight: '500',
  },
  confirmButton: {
    backgroundColor: '#10B981',
    borderRadius: wp('3%'),
    paddingVertical: hp('1.5%'),
    paddingHorizontal: wp('8%'),
    alignItems: 'center',
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  confirmButtonText: {
    color: '#FFFFFF',
    fontSize: wp('4%'),
    fontWeight: '700',
  },

  // Materials Modal Styles
  materialsModal: {
    backgroundColor: '#FFFFFF',
    borderRadius: wp('5%'),
    margin: wp('4%'),
    marginTop: hp('10%'),
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  materialsContent: {
    flex: 1,
    paddingHorizontal: wp('4%'),
    paddingBottom: hp('2%'),
  },
  closeButton: {
    padding: wp('2%'),
    borderRadius: wp('5%'),
    backgroundColor: '#F3F4F6',
    alignSelf: 'flex-end',
  },
  closeButtonText: {
    fontSize: wp('5%'),
    color: '#6B7280',
    fontWeight: '700',
  },
  topicInfo: {
    backgroundColor: '#F0F9FF',
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1%'),
    borderBottomWidth: 1,
    borderBottomColor: '#E0E7FF',
  },
  topicInfoText: {
    fontSize: wp('3.5%'),
    color: '#1E40AF',
    fontWeight: '500',
    textAlign: 'center',
  },
  materialItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: hp('1.5%'),
    paddingHorizontal: wp('4%'),
    marginVertical: hp('0.5%'),
    backgroundColor: '#F8FAFC',
    borderRadius: wp('3%'),
    borderWidth: 1,
    borderColor: '#E2E8F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 2,
    elevation: 1,
  },
  materialInfo: {
    flex: 1,
  },
  materialTitle: {
    fontSize: wp('4%'),
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: hp('0.3%'),
  },
  materialType: {
    fontSize: wp('3%'),
    color: '#6B7280',
    textTransform: 'uppercase',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  materialFileName: {
    fontSize: wp('3.2%'),
    color: '#374151',
    marginTop: hp('0.3%'),
  },
  materialDate: {
    fontSize: wp('3%'),
    color: '#9CA3AF',
    marginTop: hp('0.2%'),
  },
  materialHierarchy: {
    fontSize: wp('3%'),
    color: '#4B5563',
    fontStyle: 'italic',
    marginTop: hp('0.2%'),
  },
  downloadButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: wp('3%'),
    paddingVertical: hp('0.8%'),
    borderRadius: wp('2%'),
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  downloadButtonText: {
    color: '#FFFFFF',
    fontSize: wp('4%'),
    fontWeight: '600',
  },

  // Empty State Styles
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: hp('8%'),
  },
  emptyStateText: {
    fontSize: wp('4%'),
    color: '#9CA3AF',
    textAlign: 'center',
    fontWeight: '500',
    lineHeight: wp('5.5%'),
    marginTop: hp('2%'),
  },

  // Additional utility styles
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  spaceBetween: {
    justifyContent: 'space-between',
  },
  textCenter: {
    textAlign: 'center',
  },
  textBold: {
    fontWeight: '700',
  },
  textMuted: {
    color: '#6B7280',
  },

  // Loading styles
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: {
    fontSize: wp('4%'),
    color: '#6B7280',
    marginTop: hp('2%'),
    textAlign: 'center',
  },
});
