import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: '#FaFaFa',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#E3E3E3',
        backgroundColor: '#FFFFFF',
    },
    headerTxt: {
        fontSize: 20,
        fontWeight: '600',
        color: '#000000',
        marginLeft: 10,
    },
    BackIcon: {
        width: 19,
        height: 17,
    },
    card: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 12,
        borderRadius: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        width: '90%',
        marginLeft: 20,
        marginTop: 15,
    },
    profileContainer: {
        width: 64,
        height: 64,
        borderRadius: 32,
        overflow: 'hidden',
    },
    profileImage: {
        width: '100%',
        height: '100%',
        borderRadius: 32,
    },
    details: {
        marginLeft: 16,
        flex: 1,
    },
    name: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    phone: {
        fontSize: 16,
        color: '#777',
        marginTop: 3,
    },
    gradeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 2,
    },
    grade: {
        fontSize: 14,
        color: '#000',
        fontWeight: '600',

    },
    attendanceCard: {
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 14,
        marginTop: 20,
        alignItems: 'center',
        width: '90%',
        marginLeft: 20,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    attendanceTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: 'black',
        marginRight: 250,
    },
    percentValue: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#007bff',
        alignSelf: 'flex-start',
        marginLeft: 26,
        marginTop: 20,
    },
    attendanceDetails: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
        marginTop: 20,
    },
    attendanceItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderRadius: 8,
        minWidth: 100,
        justifyContent: 'flex-start',
    },
    attendanceIcon: {
        width: 36,
        height: 36,
        marginRight: 4,
    },
    attendanceTextContainer: {
        flexDirection: 'column',
        marginLeft: 12,
    },
    attendanceText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#555',
    },
    attendanceNumber: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'black',
        marginTop: 2,
    },
    infoCard: {
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 14,
        marginTop: 20,
        width: '90%',
        marginLeft: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    leftColumn: {
        flex: 1,
        alignItems: 'flex-start',
    },
    rightColumn: {
        flex: 1,
        alignItems: 'flex-start',
    },
    infoText: {
        fontSize: 15,
        color: '#000000',
        marginBottom: 4,
        fontWeight: '500',
        textAlign: 'left',
    },
    bold: {
        fontWeight: '600',
        color: '#555',
    },
    leaveButton: {
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 14,
        marginTop: 20,
        alignItems: 'center',
        justifyContent: 'center',
        width: 160,
        height: 90,
        marginLeft: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    leaveButtonText: {
        color: 'black',
        fontSize: 16,
        fontWeight: '600',
        marginTop: 8,
    },
    homeButton: {
        position: 'absolute',
        bottom: 30,
        right: 24,
        backgroundColor: '#AEBCFF',
        padding: 16,
        borderRadius: 35,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
        width: 60,
        height: 60,
    },
});

export default styles;