import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 20,
        paddingHorizontal: 20,
        backgroundColor: '#FFFFFF',
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        // borderBottomLeftRadius: 20,
        // borderBottomRightRadius: 20,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#1A1A1A',
        flex: 1,
        textAlign: 'center',
        marginLeft: -24, // Compensate for back button
    },
    backButtonContainer: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: 'transparent',
        justifyContent: 'center',
        alignItems: 'center',
        minWidth: 40,
        minHeight: 40,
    },
    backToListButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#007AFF',
        borderRadius: 20,
        elevation: 4,
        shadowColor: '#007AFF',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    backToListText: {
        color: '#FFFFFF',
        fontSize: 12,
        fontWeight: '600',
    },

    // Section Tabs
    sectionTabsContainer: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        // backgroundColor: '#ffffff4f',
        marginBottom: 5,
    },
    sectionTab: {
        paddingHorizontal: 24,
        paddingVertical: 8,
        borderRadius: 25,
        marginRight: 12,
        backgroundColor: '#F5F5F7',
        borderWidth: 1,
        borderColor: '#E5E5EA',
    },
    activeSectionTab: {
        backgroundColor: '#007AFF',
        borderColor: '#007AFF',
        elevation: 6,
        shadowColor: '#007AFF',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    sectionTabText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#8E8E93',
        textAlign:'center',
        marginVertical: 'auto',
    },
    activeSectionTabText: {
        color: '#FFFFFF',
    },

    // Main Content
    mainContent: {
        flex: 100,
        paddingHorizontal: 20,
        paddingTop: 10,
    },

    // Student List Styles
    studentListContainer: {
        flex: 1,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 20,
        textAlign: 'center',
    },
    studentList: {
        paddingBottom: 20,
    },
    studentItem: {
        backgroundColor: '#FFFFFF',
        padding: 20,
        marginBottom: 15,
        borderRadius: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    studentInfo: {
        flex: 1,
    },
    studentName: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1A1A1A',
        marginBottom: 6,
    },
    studentRoll: {
        fontSize: 14,
        color: '#007AFF',
        fontWeight: '600',
        marginBottom: 4,
    },
    studentDetails: {
        fontSize: 12,
        color: '#8E8E93',
        fontWeight: '500',
    },
    selectText: {
        fontSize: 14,
        color: '#007AFF',
        fontWeight: '600',
        backgroundColor: '#F0F8FF',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 12,
    },

    // Schedule View Styles
    scheduleContainer: {
        flex: 1,
    },
    scheduleControls: {
        backgroundColor: '#FFFFFF',
        padding: 20,
        borderRadius: 16,
        marginBottom: 20,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    studentInfoHeader: {
        marginBottom: 16,
        alignItems: 'center',
        paddingBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    selectedStudentName: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1A1A1A',
        textAlign: 'center',
    },
    selectedStudentRoll: {
        fontSize: 16,
        color: '#007AFF',
        fontWeight: '600',
        marginTop: 4,
        textAlign: 'center',
    },
    datePickerButton: {
        backgroundColor: '#F8F9FA',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E9ECEF',
        alignItems: 'center',
    },
    datePickerText: {
        fontSize: 16,
        color: '#495057',
        fontWeight: '600',
    },
    scheduleScrollView: {
        flex: 1,
    },

    // Period Styles
    periodContainer: {
        backgroundColor: '#FFFFFF',
        marginBottom: 16,
        borderRadius: 16,
        padding: 20,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    periodHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F0F0F0',
    },
    periodTime: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1A1A1A',
        flex: 1,
    },
    periodSubject: {
        fontSize: 15,
        color: '#007AFF',
        fontWeight: '600',
        flex: 1,
        textAlign: 'center',
        backgroundColor: '#F0F8FF',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 8,
    },
    editButtonText: {
        fontSize: 12,
        color: '#28A745',
        fontWeight: '600',
        backgroundColor: '#F0FFF4',
        paddingVertical: 6,
        paddingHorizontal: 10,
        borderRadius: 8,
    },
    activityContainer: {
        backgroundColor: '#F8F9FA',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#007AFF',
    },
    activity: {
        marginBottom: 8,
    },
    overridesContainer: {
        backgroundColor: '#FFF8E1',
        padding: 16,
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#FF9800',
    },
    overrideTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: '#E65100',
        marginBottom: 12,
    },
    overrideItem: {
        backgroundColor: '#FFFFFF',
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#FFE0B2',
    },

    // Common Styles
    centerLoader: {
        marginTop: 60,
    },
    noDataContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 60,
    },
    noDataText: {
        fontSize: 18,
        color: '#8E8E93',
        textAlign: 'center',
        fontWeight: '500',
    },
    noScheduleText: {
        fontSize: 18,
        color: '#8E8E93',
        textAlign: 'center',
        padding: 40,
        fontWeight: '500',
    },

    // Modal Styles
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.6)',
    },
    modalContent: {
        backgroundColor: '#FFFFFF',
        padding: 20,
        borderRadius: 20,
        width: '95%',
        maxWidth: 450,
        maxHeight: '90%',
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
    },
    modalScrollView: {
        flexGrow: 1,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: '700',
        marginBottom: 24,
        textAlign: 'center',
        color: '#1A1A1A',
    },
    loadingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 10,
        marginBottom: 15,
    },
    loadingText: {
        marginLeft: 10,
        fontSize: 14,
        color: '#666',
    },
    fieldContainer: {
        marginBottom: 16,
    },
    fieldLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    timeContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    timeField: {
        flex: 1,
        marginHorizontal: 4,
    },
    timePickerButton: {
        borderWidth: 2,
        borderColor: '#E9ECEF',
        padding: 16,
        borderRadius: 12,
        backgroundColor: '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: 50,
    },
    timePickerText: {
        fontSize: 16,
        color: '#495057',
        fontWeight: '500',
    },
    pickerContainer: {
        borderWidth: 2,
        borderColor: '#E9ECEF',
        borderRadius: 12,
        backgroundColor: '#F8F9FA',
        overflow: 'hidden',
    },
    picker: {
        height: 50,
        width: '100%',
        color: '#495057',
    },
    switchContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
    },
    textArea: {
        minHeight: 80,
        textAlignVertical: 'top',
    },
    input: {
        borderWidth: 2,
        borderColor: '#E9ECEF',
        padding: 16,
        borderRadius: 12,
        fontSize: 16,
        backgroundColor: '#F8F9FA',
        color: '#495057',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 20,
        paddingTop: 20,
    },
    button: {
        backgroundColor: '#007AFF',
        paddingVertical: 14,
        paddingHorizontal: 28,
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#007AFF',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        minWidth: 100,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
    },
    cancelButton: {
        backgroundColor: '#6C757D',
        shadowColor: '#6C757D',
    },
    buttonText: {
        color: '#FFFFFF',
        fontWeight: '600',
        textAlign: 'center',
        fontSize: 16,
    },
    cancelButtonText: {
        color: '#FFFFFF',
    },

    // Legacy styles for backward compatibility
    controlsContainer: {
        padding: 10,
        backgroundColor: 'white',
        borderBottomWidth: 1,
        borderColor: '#eee',
    },
    picker: {
        height: 50,
        width: '100%',
    },
    
    // New styles for schedule type indicators
    scheduleTypeIndicator: {
        backgroundColor: '#E3F2FD',
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
        borderLeftWidth: 4,
        borderLeftColor: '#2196F3',
    },
    scheduleTypeText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1976D2',
        textAlign: 'center',
    },
    studentSpecificLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#FF9800',
        backgroundColor: '#FFF3E0',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
        alignSelf: 'flex-start',
        marginTop: 4,
    },
});

export default styles;